import { ROUTE_NAMES } from '../router/routes'

export const routeNamePageChaptersMap: { [key in ROUTE_NAMES]: string[] } = {
  [ROUTE_NAMES.FORM]: [
    'Basics.md',
    'Basics - Basic Example.vue',
    'Basics - Advanced Example.vue',
    'Frameworks.md',
    'Frameworks - Quasar Framework.vue',
    'Slots.md',
    'Slots - Default.vue',
    'Slots - Label.vue',
    'Modes.vue',
    'Modes - Disable fields on view mode.vue',
    'Action Buttons.md',
    'Action Buttons - Pre-made action buttons.vue',
    'Action Buttons - Overwriting pre-made action buttons.vue',
    'Action Buttons - Custom action buttons.vue',
    'Styling via CSS.vue',
    'Events.md',
    'Events - Form events.vue',
    'Events - Field events.vue',
    'Events - Update other fields on events.vue',
    'Nested Data.vue',
    'Evaluated Props.md',
    'Evaluated Props - 1.vue',
    'Evaluated Props - 2.vue',
    'Evaluated Props - 3.vue',
    'Evaluated Props - 4.vue',
    'Evaluated Props - 5.vue',
    'Computed Fields.md',
    'Computed Fields - 1.vue',
    'Computed Fields - 2.vue',
    'Computed Fields - 3.vue',
    'Validation.vue',
    'Validation - 2.vue',
  ],
  [ROUTE_NAMES.TABLE]: [
    'Basics.vue',
    'Advanced.vue',
    'Computed Columns.vue',
    'Selection.vue',
    'Slots.vue',
    'Edit on Button Click.vue',
    'Edit on Row Click.vue',
    'Styling via CSS.vue',
  ],
}
